device:
  ip: "<Your device IP (i.e. 192.168.0.1)>" # Replace with your local Roku TV IP
  port: "8060"                              # Optional: Port for network requests (default: 8060)        
  timeout: 5                                # Timeout for network requests (in seconds)

content:
  video_ids: [                              # Replace with Youtube video IDs to play
    "<Youtube ID>",
  ]

time:
  days: [
    monday: [
      "<Time>"                              # Replace with time to play video (i.e. "09:00")
    ],
    tuesday: [
      "<Time>" 
    ],
    wednesday: [
      "<Time>" 
    ],
    thursday: [
      "<Time>" 
    ],
    friday: [
      "<Time>" 
    ],
    saturday: [
      "<Time>" 
    ],
    sunday: [
      "<Time>" 
    ]
  ]